#!/bin/sh
PATH="/usr/local/openresty/nginx/sbin:/usr/local/opt/openresty/bin:/usr/sbin:$PATH"
sed s/%PORT%/${PORT-8080}/ nginx.conf >nginx.conf.compiled
if command -v nginx 1>/dev/null && nginx -V 2>&1 | grep -q openresty; then
    COMMAND="nginx -p $(pwd) -c nginx.conf.compiled"
    case "$1" in
        reload)
            $COMMAND -s reload
            ;;
        *)
            mkdir -p logs
            touch logs/error.log
            touch logs/access.log
            mkdir -p tmp
            $COMMAND
            ;;
    esac
else
    echo "OpenResty not found"
    exit 1
fi