#!/bin/sh
PATH="/usr/local/openresty/nginx/sbin:/usr/local/opt/openresty/bin:/usr/sbin:$PATH"
# Compile templates
for TEMPLATE in templates/*.tpl; do
    templatec $TEMPLATE -o ${TEMPLATE%.*}.lua
done
for TEMPLATE in templates/*/*.tpl; do
    templatec $TEMPLATE -o ${TEMPLATE%.*}.lua
done
# Compile nginx config
sed s/%PORT%/${PORT-8080}/g nginx.conf >nginx.conf.compiled
# Check if nginx exists and has ngx_openresty module
if command -v nginx 1>/dev/null && nginx -V 2>&1 | grep -q openresty; then
    COMMAND="nginx -p $(pwd) -c nginx.conf.compiled"
    case "$1" in
        reload)
            $COMMAND -s reload
            ;;
        *)
            mkdir -p logs
            touch logs/error.log
            touch logs/access.log
            mkdir -p tmp
            $COMMAND
            ;;
    esac
else
    echo "OpenResty not found"
    exit 1
fi